# Locale (en, cs)
locale: en

allow-crafting: false
keep-inventory-on-death: false
in-lobby-colored-leather-by-team: true
jointeam-entity-show-name: true

# Commands whitelist
allowed-commands:
- "/help"

# Ignored blocks (Farm blocks)
farmBlocks:
  enable: true
  blocks:
  - WHEAT
  - CARROTS
  - POTATOES
  - BEETROOTS

# Scoreboard settings
scoreboard:
  enable: true
  title: "§a%game%§r - %time%"
  bedLost: "§c\u2718"
  bedExists: "§a\u2714"
  teamTitle: "%bed%%color%%team%"
  
# Title speed
title:
  fadeIn: 0
  stay: 20
  fadeOut: 0
  
# Items
items:
  jointeam: COMPASS
  leavegame: SLIME_BALL
  shopback: BARRIER
  
# Vault rewards
vault:
  enable: true
  reward:
    kill: 5
    win: 20
  
# Resources
resources:
  bronze:
    material: BRICK
    interval: 1
    name: "Bronze"
    translate: "resource_bronze"
    color: DARK_RED
    spread: 1.0
  iron:
    material: IRON_INGOT
    interval: 10
    name: "Iron"
    translate: "resource_iron"
    color: GRAY
    spread: 1.0
  gold:
    material: GOLD_INGOT
    interval: 20
    name: "Gold"
    translate: "resource_gold"
    color: GOLD
    spread: 1.0
  
# Do not edit this!!!
version: 2